[client]
environment = "development"
name = "document-storage-back"
version = "0.0.1"
max_retries = 3
timeout = 3600

[connection]
host = "localhost"
port = 5672
protocol = "tcp"
keep_alive = true
heartbeat_interval = 3600
reconnect_backoff = 3600
max_reconnect_attempts = 5

[transport]
type = "tcp"
buffer_size = 1024
compression_enabled = false
compression_level = 6

[observability.logging]
level = "debug"
format = "text"

[security.tls]
insecure_skip_verify = true
