// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/hopper/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSerializer creates a new instance of MockSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSerializer {
	mock := &MockSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSerializer is an autogenerated mock type for the Serializer type
type MockSerializer struct {
	mock.Mock
}

type MockSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSerializer) EXPECT() *MockSerializer_Expecter {
	return &MockSerializer_Expecter{mock: &_m.Mock}
}

// DeserializeFrame provides a mock function for the type MockSerializer
func (_mock *MockSerializer) DeserializeFrame(data []byte) (domain.Frame, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeFrame")
	}

	var r0 domain.Frame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (domain.Frame, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) domain.Frame); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Frame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSerializer_DeserializeFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeserializeFrame'
type MockSerializer_DeserializeFrame_Call struct {
	*mock.Call
}

// DeserializeFrame is a helper method to define mock.On call
//   - data []byte
func (_e *MockSerializer_Expecter) DeserializeFrame(data interface{}) *MockSerializer_DeserializeFrame_Call {
	return &MockSerializer_DeserializeFrame_Call{Call: _e.mock.On("DeserializeFrame", data)}
}

func (_c *MockSerializer_DeserializeFrame_Call) Run(run func(data []byte)) *MockSerializer_DeserializeFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSerializer_DeserializeFrame_Call) Return(frame domain.Frame, err error) *MockSerializer_DeserializeFrame_Call {
	_c.Call.Return(frame, err)
	return _c
}

func (_c *MockSerializer_DeserializeFrame_Call) RunAndReturn(run func(data []byte) (domain.Frame, error)) *MockSerializer_DeserializeFrame_Call {
	_c.Call.Return(run)
	return _c
}

// SerializeFrame provides a mock function for the type MockSerializer
func (_mock *MockSerializer) SerializeFrame() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SerializeFrame")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSerializer_SerializeFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SerializeFrame'
type MockSerializer_SerializeFrame_Call struct {
	*mock.Call
}

// SerializeFrame is a helper method to define mock.On call
func (_e *MockSerializer_Expecter) SerializeFrame() *MockSerializer_SerializeFrame_Call {
	return &MockSerializer_SerializeFrame_Call{Call: _e.mock.On("SerializeFrame")}
}

func (_c *MockSerializer_SerializeFrame_Call) Run(run func()) *MockSerializer_SerializeFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSerializer_SerializeFrame_Call) Return(bytes []byte, err error) *MockSerializer_SerializeFrame_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSerializer_SerializeFrame_Call) RunAndReturn(run func() ([]byte, error)) *MockSerializer_SerializeFrame_Call {
	_c.Call.Return(run)
	return _c
}
