// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/hopper/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectFramePayload creates a new instance of MockConnectFramePayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectFramePayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectFramePayload {
	mock := &MockConnectFramePayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectFramePayload is an autogenerated mock type for the ConnectFramePayload type
type MockConnectFramePayload struct {
	mock.Mock
}

type MockConnectFramePayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectFramePayload) EXPECT() *MockConnectFramePayload_Expecter {
	return &MockConnectFramePayload_Expecter{mock: &_m.Mock}
}

// GetClientID provides a mock function for the type MockConnectFramePayload
func (_mock *MockConnectFramePayload) GetClientID() domain.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientID")
	}

	var r0 domain.ID
	if returnFunc, ok := ret.Get(0).(func() domain.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ID)
	}
	return r0
}

// MockConnectFramePayload_GetClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientID'
type MockConnectFramePayload_GetClientID_Call struct {
	*mock.Call
}

// GetClientID is a helper method to define mock.On call
func (_e *MockConnectFramePayload_Expecter) GetClientID() *MockConnectFramePayload_GetClientID_Call {
	return &MockConnectFramePayload_GetClientID_Call{Call: _e.mock.On("GetClientID")}
}

func (_c *MockConnectFramePayload_GetClientID_Call) Run(run func()) *MockConnectFramePayload_GetClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectFramePayload_GetClientID_Call) Return(iD domain.ID) *MockConnectFramePayload_GetClientID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockConnectFramePayload_GetClientID_Call) RunAndReturn(run func() domain.ID) *MockConnectFramePayload_GetClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientVersion provides a mock function for the type MockConnectFramePayload
func (_mock *MockConnectFramePayload) GetClientVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConnectFramePayload_GetClientVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientVersion'
type MockConnectFramePayload_GetClientVersion_Call struct {
	*mock.Call
}

// GetClientVersion is a helper method to define mock.On call
func (_e *MockConnectFramePayload_Expecter) GetClientVersion() *MockConnectFramePayload_GetClientVersion_Call {
	return &MockConnectFramePayload_GetClientVersion_Call{Call: _e.mock.On("GetClientVersion")}
}

func (_c *MockConnectFramePayload_GetClientVersion_Call) Run(run func()) *MockConnectFramePayload_GetClientVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectFramePayload_GetClientVersion_Call) Return(s string) *MockConnectFramePayload_GetClientVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConnectFramePayload_GetClientVersion_Call) RunAndReturn(run func() string) *MockConnectFramePayload_GetClientVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeader provides a mock function for the type MockConnectFramePayload
func (_mock *MockConnectFramePayload) GetHeader() domain.HeaderPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeader")
	}

	var r0 domain.HeaderPayload
	if returnFunc, ok := ret.Get(0).(func() domain.HeaderPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.HeaderPayload)
		}
	}
	return r0
}

// MockConnectFramePayload_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type MockConnectFramePayload_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *MockConnectFramePayload_Expecter) GetHeader() *MockConnectFramePayload_GetHeader_Call {
	return &MockConnectFramePayload_GetHeader_Call{Call: _e.mock.On("GetHeader")}
}

func (_c *MockConnectFramePayload_GetHeader_Call) Run(run func()) *MockConnectFramePayload_GetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectFramePayload_GetHeader_Call) Return(headerPayload domain.HeaderPayload) *MockConnectFramePayload_GetHeader_Call {
	_c.Call.Return(headerPayload)
	return _c
}

func (_c *MockConnectFramePayload_GetHeader_Call) RunAndReturn(run func() domain.HeaderPayload) *MockConnectFramePayload_GetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeepAlive provides a mock function for the type MockConnectFramePayload
func (_mock *MockConnectFramePayload) GetKeepAlive() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeepAlive")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockConnectFramePayload_GetKeepAlive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeepAlive'
type MockConnectFramePayload_GetKeepAlive_Call struct {
	*mock.Call
}

// GetKeepAlive is a helper method to define mock.On call
func (_e *MockConnectFramePayload_Expecter) GetKeepAlive() *MockConnectFramePayload_GetKeepAlive_Call {
	return &MockConnectFramePayload_GetKeepAlive_Call{Call: _e.mock.On("GetKeepAlive")}
}

func (_c *MockConnectFramePayload_GetKeepAlive_Call) Run(run func()) *MockConnectFramePayload_GetKeepAlive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectFramePayload_GetKeepAlive_Call) Return(v uint16) *MockConnectFramePayload_GetKeepAlive_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConnectFramePayload_GetKeepAlive_Call) RunAndReturn(run func() uint16) *MockConnectFramePayload_GetKeepAlive_Call {
	_c.Call.Return(run)
	return _c
}

// Sizer provides a mock function for the type MockConnectFramePayload
func (_mock *MockConnectFramePayload) Sizer() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sizer")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockConnectFramePayload_Sizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sizer'
type MockConnectFramePayload_Sizer_Call struct {
	*mock.Call
}

// Sizer is a helper method to define mock.On call
func (_e *MockConnectFramePayload_Expecter) Sizer() *MockConnectFramePayload_Sizer_Call {
	return &MockConnectFramePayload_Sizer_Call{Call: _e.mock.On("Sizer")}
}

func (_c *MockConnectFramePayload_Sizer_Call) Run(run func()) *MockConnectFramePayload_Sizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnectFramePayload_Sizer_Call) Return(v uint16) *MockConnectFramePayload_Sizer_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockConnectFramePayload_Sizer_Call) RunAndReturn(run func() uint16) *MockConnectFramePayload_Sizer_Call {
	_c.Call.Return(run)
	return _c
}
