// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/hopper/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenFramePayload creates a new instance of MockOpenFramePayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenFramePayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenFramePayload {
	mock := &MockOpenFramePayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenFramePayload is an autogenerated mock type for the OpenFramePayload type
type MockOpenFramePayload struct {
	mock.Mock
}

type MockOpenFramePayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenFramePayload) EXPECT() *MockOpenFramePayload_Expecter {
	return &MockOpenFramePayload_Expecter{mock: &_m.Mock}
}

// GetAssignedContainerID provides a mock function for the type MockOpenFramePayload
func (_mock *MockOpenFramePayload) GetAssignedContainerID() domain.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAssignedContainerID")
	}

	var r0 domain.ID
	if returnFunc, ok := ret.Get(0).(func() domain.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ID)
	}
	return r0
}

// MockOpenFramePayload_GetAssignedContainerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssignedContainerID'
type MockOpenFramePayload_GetAssignedContainerID_Call struct {
	*mock.Call
}

// GetAssignedContainerID is a helper method to define mock.On call
func (_e *MockOpenFramePayload_Expecter) GetAssignedContainerID() *MockOpenFramePayload_GetAssignedContainerID_Call {
	return &MockOpenFramePayload_GetAssignedContainerID_Call{Call: _e.mock.On("GetAssignedContainerID")}
}

func (_c *MockOpenFramePayload_GetAssignedContainerID_Call) Run(run func()) *MockOpenFramePayload_GetAssignedContainerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenFramePayload_GetAssignedContainerID_Call) Return(iD domain.ID) *MockOpenFramePayload_GetAssignedContainerID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockOpenFramePayload_GetAssignedContainerID_Call) RunAndReturn(run func() domain.ID) *MockOpenFramePayload_GetAssignedContainerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeader provides a mock function for the type MockOpenFramePayload
func (_mock *MockOpenFramePayload) GetHeader() domain.HeaderPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeader")
	}

	var r0 domain.HeaderPayload
	if returnFunc, ok := ret.Get(0).(func() domain.HeaderPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.HeaderPayload)
		}
	}
	return r0
}

// MockOpenFramePayload_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type MockOpenFramePayload_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *MockOpenFramePayload_Expecter) GetHeader() *MockOpenFramePayload_GetHeader_Call {
	return &MockOpenFramePayload_GetHeader_Call{Call: _e.mock.On("GetHeader")}
}

func (_c *MockOpenFramePayload_GetHeader_Call) Run(run func()) *MockOpenFramePayload_GetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenFramePayload_GetHeader_Call) Return(headerPayload domain.HeaderPayload) *MockOpenFramePayload_GetHeader_Call {
	_c.Call.Return(headerPayload)
	return _c
}

func (_c *MockOpenFramePayload_GetHeader_Call) RunAndReturn(run func() domain.HeaderPayload) *MockOpenFramePayload_GetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceID provides a mock function for the type MockOpenFramePayload
func (_mock *MockOpenFramePayload) GetSourceID() domain.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourceID")
	}

	var r0 domain.ID
	if returnFunc, ok := ret.Get(0).(func() domain.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ID)
	}
	return r0
}

// MockOpenFramePayload_GetSourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceID'
type MockOpenFramePayload_GetSourceID_Call struct {
	*mock.Call
}

// GetSourceID is a helper method to define mock.On call
func (_e *MockOpenFramePayload_Expecter) GetSourceID() *MockOpenFramePayload_GetSourceID_Call {
	return &MockOpenFramePayload_GetSourceID_Call{Call: _e.mock.On("GetSourceID")}
}

func (_c *MockOpenFramePayload_GetSourceID_Call) Run(run func()) *MockOpenFramePayload_GetSourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenFramePayload_GetSourceID_Call) Return(iD domain.ID) *MockOpenFramePayload_GetSourceID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockOpenFramePayload_GetSourceID_Call) RunAndReturn(run func() domain.ID) *MockOpenFramePayload_GetSourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Sizer provides a mock function for the type MockOpenFramePayload
func (_mock *MockOpenFramePayload) Sizer() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sizer")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockOpenFramePayload_Sizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sizer'
type MockOpenFramePayload_Sizer_Call struct {
	*mock.Call
}

// Sizer is a helper method to define mock.On call
func (_e *MockOpenFramePayload_Expecter) Sizer() *MockOpenFramePayload_Sizer_Call {
	return &MockOpenFramePayload_Sizer_Call{Call: _e.mock.On("Sizer")}
}

func (_c *MockOpenFramePayload_Sizer_Call) Run(run func()) *MockOpenFramePayload_Sizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenFramePayload_Sizer_Call) Return(v uint16) *MockOpenFramePayload_Sizer_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockOpenFramePayload_Sizer_Call) RunAndReturn(run func() uint16) *MockOpenFramePayload_Sizer_Call {
	_c.Call.Return(run)
	return _c
}
