// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/hopper/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPayload creates a new instance of MockPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayload {
	mock := &MockPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPayload is an autogenerated mock type for the Payload type
type MockPayload struct {
	mock.Mock
}

type MockPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayload) EXPECT() *MockPayload_Expecter {
	return &MockPayload_Expecter{mock: &_m.Mock}
}

// GetHeader provides a mock function for the type MockPayload
func (_mock *MockPayload) GetHeader() domain.HeaderPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeader")
	}

	var r0 domain.HeaderPayload
	if returnFunc, ok := ret.Get(0).(func() domain.HeaderPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.HeaderPayload)
		}
	}
	return r0
}

// MockPayload_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type MockPayload_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *MockPayload_Expecter) GetHeader() *MockPayload_GetHeader_Call {
	return &MockPayload_GetHeader_Call{Call: _e.mock.On("GetHeader")}
}

func (_c *MockPayload_GetHeader_Call) Run(run func()) *MockPayload_GetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPayload_GetHeader_Call) Return(headerPayload domain.HeaderPayload) *MockPayload_GetHeader_Call {
	_c.Call.Return(headerPayload)
	return _c
}

func (_c *MockPayload_GetHeader_Call) RunAndReturn(run func() domain.HeaderPayload) *MockPayload_GetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// Sizer provides a mock function for the type MockPayload
func (_mock *MockPayload) Sizer() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sizer")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockPayload_Sizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sizer'
type MockPayload_Sizer_Call struct {
	*mock.Call
}

// Sizer is a helper method to define mock.On call
func (_e *MockPayload_Expecter) Sizer() *MockPayload_Sizer_Call {
	return &MockPayload_Sizer_Call{Call: _e.mock.On("Sizer")}
}

func (_c *MockPayload_Sizer_Call) Run(run func()) *MockPayload_Sizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPayload_Sizer_Call) Return(v uint16) *MockPayload_Sizer_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPayload_Sizer_Call) RunAndReturn(run func() uint16) *MockPayload_Sizer_Call {
	_c.Call.Return(run)
	return _c
}
