// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/hopper/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenRcvdFramePayload creates a new instance of MockOpenRcvdFramePayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenRcvdFramePayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenRcvdFramePayload {
	mock := &MockOpenRcvdFramePayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpenRcvdFramePayload is an autogenerated mock type for the OpenRcvdFramePayload type
type MockOpenRcvdFramePayload struct {
	mock.Mock
}

type MockOpenRcvdFramePayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenRcvdFramePayload) EXPECT() *MockOpenRcvdFramePayload_Expecter {
	return &MockOpenRcvdFramePayload_Expecter{mock: &_m.Mock}
}

// GetHeader provides a mock function for the type MockOpenRcvdFramePayload
func (_mock *MockOpenRcvdFramePayload) GetHeader() domain.HeaderPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeader")
	}

	var r0 domain.HeaderPayload
	if returnFunc, ok := ret.Get(0).(func() domain.HeaderPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.HeaderPayload)
		}
	}
	return r0
}

// MockOpenRcvdFramePayload_GetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeader'
type MockOpenRcvdFramePayload_GetHeader_Call struct {
	*mock.Call
}

// GetHeader is a helper method to define mock.On call
func (_e *MockOpenRcvdFramePayload_Expecter) GetHeader() *MockOpenRcvdFramePayload_GetHeader_Call {
	return &MockOpenRcvdFramePayload_GetHeader_Call{Call: _e.mock.On("GetHeader")}
}

func (_c *MockOpenRcvdFramePayload_GetHeader_Call) Run(run func()) *MockOpenRcvdFramePayload_GetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenRcvdFramePayload_GetHeader_Call) Return(headerPayload domain.HeaderPayload) *MockOpenRcvdFramePayload_GetHeader_Call {
	_c.Call.Return(headerPayload)
	return _c
}

func (_c *MockOpenRcvdFramePayload_GetHeader_Call) RunAndReturn(run func() domain.HeaderPayload) *MockOpenRcvdFramePayload_GetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceID provides a mock function for the type MockOpenRcvdFramePayload
func (_mock *MockOpenRcvdFramePayload) GetSourceID() domain.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourceID")
	}

	var r0 domain.ID
	if returnFunc, ok := ret.Get(0).(func() domain.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ID)
	}
	return r0
}

// MockOpenRcvdFramePayload_GetSourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceID'
type MockOpenRcvdFramePayload_GetSourceID_Call struct {
	*mock.Call
}

// GetSourceID is a helper method to define mock.On call
func (_e *MockOpenRcvdFramePayload_Expecter) GetSourceID() *MockOpenRcvdFramePayload_GetSourceID_Call {
	return &MockOpenRcvdFramePayload_GetSourceID_Call{Call: _e.mock.On("GetSourceID")}
}

func (_c *MockOpenRcvdFramePayload_GetSourceID_Call) Run(run func()) *MockOpenRcvdFramePayload_GetSourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenRcvdFramePayload_GetSourceID_Call) Return(iD domain.ID) *MockOpenRcvdFramePayload_GetSourceID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockOpenRcvdFramePayload_GetSourceID_Call) RunAndReturn(run func() domain.ID) *MockOpenRcvdFramePayload_GetSourceID_Call {
	_c.Call.Return(run)
	return _c
}

// Sizer provides a mock function for the type MockOpenRcvdFramePayload
func (_mock *MockOpenRcvdFramePayload) Sizer() uint16 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sizer")
	}

	var r0 uint16
	if returnFunc, ok := ret.Get(0).(func() uint16); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint16)
	}
	return r0
}

// MockOpenRcvdFramePayload_Sizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sizer'
type MockOpenRcvdFramePayload_Sizer_Call struct {
	*mock.Call
}

// Sizer is a helper method to define mock.On call
func (_e *MockOpenRcvdFramePayload_Expecter) Sizer() *MockOpenRcvdFramePayload_Sizer_Call {
	return &MockOpenRcvdFramePayload_Sizer_Call{Call: _e.mock.On("Sizer")}
}

func (_c *MockOpenRcvdFramePayload_Sizer_Call) Run(run func()) *MockOpenRcvdFramePayload_Sizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOpenRcvdFramePayload_Sizer_Call) Return(v uint16) *MockOpenRcvdFramePayload_Sizer_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockOpenRcvdFramePayload_Sizer_Call) RunAndReturn(run func() uint16) *MockOpenRcvdFramePayload_Sizer_Call {
	_c.Call.Return(run)
	return _c
}
